server:
  port: 9001

spring:
  datasource:
    url: jdbc:hsqldb:mem:Bank
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    jpa:
      hibernate:
        ddl-auto: update
    generate-ddl: true
